### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 1. Create account
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "phoneNumber": "0712345678",
  "fullName": "Alice Wanjiru",
  "tier": "BASIC"
}

### 2. Get account  ← paste the id from step 1 here
GET http://localhost:8080/accounts/1b63828b-6d3b-4f43-bbd7-25201d295ac5

### 3. Get balance
GET http://localhost:8080/accounts/1b63828b-6d3b-4f43-bbd7-25201d295ac5/balance

### 4. Deposit
POST http://localhost:8080/accounts/1b63828b-6d3b-4f43-bbd7-25201d295ac5/deposit
Content-Type: application/json

{
  "amount": 5000,
  "description": "Initial deposit"
}

### 5. Withdraw
POST http://localhost:8080/accounts/1b63828b-6d3b-4f43-bbd7-25201d295ac5/withdraw
Content-Type: application/json

{
  "amount": 1000,
  "description": "Test withdrawal"
}

### 6. Suspend account
PATCH http://localhost:8080/accounts/1b63828b-6d3b-4f43-bbd7-25201d295ac5/status
Content-Type: application/json

{
  "status": "SUSPENDED"
}

### 7. Try deposit on suspended account — should return 403
POST http://localhost:8080/accounts/1b63828b-6d3b-4f43-bbd7-25201d295ac5/deposit
Content-Type: application/json

{
  "amount": 1000,
  "description": "This should fail"
}

### 8. Reactivate account
PATCH http://localhost:8080/accounts/1b63828b-6d3b-4f43-bbd7-25201d295ac5/status
Content-Type: application/json

{
  "status": "ACTIVE"
}

### 9. Upgrade tier
PUT http://localhost:8080/accounts/1b63828b-6d3b-4f43-bbd7-25201d295ac5/tier
Content-Type: application/json

{
  "tier": "STANDARD"
}
